/**
 * World language catalogue for the language picker.
 *
 * The data (src/data/languages.json) is generated by scripts/build-languages.mjs
 * from ISO 639-3 (SIL), Glottolog (CC-BY 4.0) and Unicode CLDR. It holds about
 * 8,700 languages — living, extinct, ancient/historical, constructed and sign
 * languages — with ~13,600 dialects and varieties. It is loaded lazily the
 * first time the picker opens so it does not slow down app start-up.
 */

// Status bit flags — kept in sync with scripts/build-languages.mjs
export const STATUS = { living: 1, extinct: 2, historical: 8, constructed: 16, sign: 32 } as const;

const REGION_NAMES = {
  F: 'Africa',
  A: 'Americas',
  S: 'Asia',
  E: 'Europe',
  M: 'Middle East',
  O: 'Oceania',
} as const;

export type Category =
  | (typeof REGION_NAMES)[keyof typeof REGION_NAMES]
  | 'Sign languages'
  | 'Ancient & historical'
  | 'Extinct'
  | 'Constructed';

export const CATEGORIES: Category[] = [
  'Africa',
  'Americas',
  'Asia',
  'Europe',
  'Middle East',
  'Oceania',
  'Sign languages',
  'Ancient & historical',
  'Extinct',
  'Constructed',
];

export interface Language {
  code: string; // ISO 639-3, Glottocode, or x-… for curated extras
  name: string; // English name — what gets stored on a deck
  native: string;
  status: number;
  countries: string[]; // ISO 3166 alpha-2
  categories: Set<Category>;
  pop: number; // approximate speakers (0 = unknown)
  family?: string;
  macro?: Language; // e.g. Egyptian Arabic → Arabic
  members: Language[]; // e.g. Arabic → Egyptian Arabic, Gulf Arabic…
  aliases: string[];
  dialects: string[];
  search: string; // folded text used for matching
}

export interface Variety {
  name: string; // as listed, e.g. "Zezuru"
  value: string; // stored on the deck, e.g. "Zezuru (Shona)"
  language: Language;
  search: string;
}

export interface Country {
  code: string;
  name: string;
  search: string;
}

export interface LanguageData {
  languages: Language[]; // most spoken first
  varieties: Variety[];
  countries: Country[];
  countryName: (code: string) => string;
  generated: string;
}

type Row = [
  code: string,
  name: string,
  native: string,
  status: number,
  countries?: string,
  pop?: number,
  family?: number,
  macro?: string,
  aliases?: string,
  dialects?: string,
];

interface RawData {
  generated: string;
  families: string[];
  regions: Record<string, keyof typeof REGION_NAMES>;
  langs: Row[];
}

export const fold = (s: string) =>
  s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[’ʼ']/g, "'");

const makeCountryName = () => {
  let names: Intl.DisplayNames | null = null;
  try {
    names = new Intl.DisplayNames(['en'], { type: 'region' });
  } catch {
    names = null;
  }
  const cache = new Map<string, string>();
  return (code: string) => {
    let n = cache.get(code);
    if (!n) {
      try {
        n = names?.of(code) ?? code;
      } catch {
        n = code;
      }
      cache.set(code, n);
    }
    return n;
  };
};

/** How a dialect is stored: keep its name if it already mentions the language. */
export const varietyValue = (dialect: string, language: string) =>
  fold(dialect).includes(fold(language.split(' (')[0])) ? dialect : `${dialect} (${language})`;

const build = (raw: RawData): LanguageData => {
  const countryName = makeCountryName();
  const byCode = new Map<string, Language>();
  const macroCodes = new Map<Language, string>();

  const languages = raw.langs.map((r): Language => {
    const [code, name, native, status, countries = '', pop = 0, family = -1, macro = '', aliases = '', dialects = ''] = r;
    const countryList = countries ? countries.split(' ') : [];
    const categories = new Set<Category>();
    for (const c of countryList) {
      const region = raw.regions[c];
      if (region) categories.add(REGION_NAMES[region]);
    }
    if (status & STATUS.sign) categories.add('Sign languages');
    if (status & STATUS.historical) categories.add('Ancient & historical');
    if (status & STATUS.extinct) categories.add('Extinct');
    if (status & STATUS.constructed) categories.add('Constructed');

    const aliasList = aliases ? aliases.split('|') : [];
    const lang: Language = {
      code,
      name,
      native,
      status,
      countries: countryList,
      categories,
      pop,
      family: family >= 0 ? raw.families[family] : undefined,
      members: [],
      aliases: aliasList,
      dialects: dialects ? dialects.split('|') : [],
      search: fold(
        [name, native, ...aliasList, family >= 0 ? raw.families[family] : '', ...countryList.map(countryName)].join(' | ')
      ),
    };
    byCode.set(code, lang);
    if (macro) macroCodes.set(lang, macro);
    return lang;
  });

  for (const [lang, macroCode] of macroCodes) {
    const macro = byCode.get(macroCode);
    if (macro) {
      lang.macro = macro;
      macro.members.push(lang);
    }
  }

  const varieties: Variety[] = languages.flatMap((language) =>
    language.dialects.map((name) => ({
      name,
      value: varietyValue(name, language.name),
      language,
      search: fold(name),
    }))
  );

  const countries = [...new Set(languages.flatMap((l) => l.countries))]
    .map((code) => ({ code, name: countryName(code), search: fold(countryName(code)) }))
    .sort((a, b) => a.name.localeCompare(b.name));

  return { languages, varieties, countries, countryName, generated: raw.generated };
};

let loading: Promise<LanguageData> | null = null;

/** Load (once) and index the language catalogue. */
export const loadLanguages = (): Promise<LanguageData> => {
  loading ??= import('../data/languages.json')
    .then((m) => build(m.default as unknown as RawData))
    .catch((e) => {
      loading = null; // allow a retry
      throw e;
    });
  return loading;
};

export const formatSpeakers = (n: number): string => {
  if (n >= 1e9) return `${(n / 1e9).toFixed(1).replace(/\.0$/, '')}B speakers`;
  if (n >= 1e6) return `${(n / 1e6).toFixed(n >= 1e7 ? 0 : 1).replace(/\.0$/, '')}M speakers`;
  if (n >= 1e3) return `${Math.round(n / 1e3)}K speakers`;
  return '';
};

export const statusLabel = (status: number): string | null => {
  if (status & STATUS.constructed) return 'Constructed';
  if (status & STATUS.historical) return 'Ancient & historical';
  if (status & STATUS.extinct) return 'Extinct';
  if (status & STATUS.sign) return 'Sign language';
  return null;
};
